rokka.settings:
  type: config_object
  mapping:
    is_enabled:
      type: boolean
      label: 'Enable Rokka'
    api_key:
      type: string
      label: 'API Key'
    api_endpoint:
      type: string
      label: 'API Key'
    jpg_quality:
      type: string
      label: 'Default JPG quality'
    webp_quality:
      type: string
      label: 'Default WEBP quality'
    autoformat:
      type: string
      label: 'Default autoformat value'
    organization_name:
      type: string
      label: 'Organization Name'
    stack_prefix:
      type: string
      label: 'Stack Name Prefix'
