rokka.settings:
  type: config_object
  mapping:
    is_enabled:
      type: boolean
      label: 'Enable Rokka'
    api_key:
      type: string
      label: 'API Key'
    api_endpoint:
      type: string
      label: 'API Key'
    organization_name:
      type: string
      label: 'Organization Name'
