rokka.settings:
  type: config_object
  mapping:
    is_enabled:
      type: boolean
      label: 'Enable Rokka'
    rokka_api_key:
      type: string
      label: 'API Key'
    rokka_secret_key:
      type: string
      label: 'Secret Key'
    organization_name:
      type: string
      label: 'Organization Name'
