rokka.rokka_stack.*:
  type: config_entity
  label: 'Rokka stack config'
  mapping:
    id:
      type: string
      label: 'Image Style Name'
    organization:
      type: string
      label: 'Organization'
    options:
      type: array
      label: 'Options'
    output_format:
      type: string
      label: 'Default output format'
    operations:
      type: array
      label: 'Operations'
    uuid:
      type: string
